version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - ALPHA_VANTAGE_KEY= API KEY
      - NEWSAPI_KEY= API KEY
    ports:
      - "5000:5000"  # Critical for external access
    networks:
      - stock-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - stock-network

networks:
  stock-network:
